language: cpp
sudo: required
services:
  - docker

dist: trusty
branches:
    only:
        - develop
        - /^develop-.*$/
        - master
        - release

env:
    - THECORE_THIRDPARTY_DIR=~/theCore_thirdparty THECORE_BUILD_THIRDPARTY_DIR=~/theCore_thirdparty_worktrees

before_install:
    - docker pull thecoreembedded/thecore

install:
    - docker run -v $(pwd):/root/thecore -w /root/thecore --name "thecore_container" -t -d thecoreembedded/thecore
    - docker ps -a

script:
    - docker exec -e THECORE_THIRDPARTY_DIR="$THECORE_THIRDPARTY_DIR" -e THECORE_BUILD_THIRDPARTY_DIR="$THECORE_BUILD_THIRDPARTY_DIR" -it thecore_container nix-shell --run ./scripts/ci_test.sh

after_script:
    - docker exec -e TRAVIS_PULL_REQUEST="$TRAVIS_PULL_REQUEST" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" -e TRAVIS_COMMIT="$TRAVIS_COMMIT" -e TRAVIS_BUILD_NUMBER="$TRAVIS_BUILD_NUMBER" -e GH_TOKEN="$GH_TOKEN" -it thecore_container nix-shell --run ./scripts/doc_deploy.sh
    - docker kill thecore_container
    - docker rm thecore_container
