language: cpp
sudo: required
dist: trusty
branches:
    only:
        - develop
        - master

install:
    - curl https://nixos.org/nix/install | sh
    - . $HOME/.nix-profile/etc/profile.d/nix.sh
    - nix-shell --pure --run true

script: nix-shell --pure --run ./scripts/ci_test.sh
